@url = http://localhost:3000

# @name register
POST {{url}}/api/authentication/register  
Content-Type: application/json

{
  "first_name": "Marcelo",
  "last_name": "Oliveto",
  "email": "marcelo.oliveto@gmail.com",
  "age": 53,
  "role": "admin",
  "password" : "12345"
}
###

# @name register_User
POST {{url}}/api/authentication/register  
Content-Type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "email": "test@gmail.com",
  "age": 25,
  "role": "user",
  "password" : "12345"
}
###

# @name register_AnotherUserWithoutRole
POST {{url}}/api/authentication/register  
Content-Type: application/json

{
  "first_name": "test1",
  "last_name": "test1",
  "email": "test1@gmail.com",
  "age": 25,
  "password" : "12345"
}
###

# @name login

POST {{url}}/api/authentication/login 
Content-Type: application/json

{
    "email": "marcelo.oliveto@gmail.com",
    "password" : "12345"
}
###

@access_token = {{login.response.body.token}}

# @name users

GET {{url}}/api/users
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###
@first = {{users.response.body.0._id}}

GET {{url}}/api/products/insertion  
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###

GET {{url}}/api/products/
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###
# @name products
GET {{url}}/api/products?limit=10&page=2&sort=asc
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###
@product1 = {{products.response.body.payload.0._id}}

GET {{url}}/api/products/{{product1}}
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###
# @name newProduct
POST {{url}}/api/products/
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
  "name" : "Coca cola",
  "description" : "Bebida cola",
  "price" : 101.10,
  "thumbnail" : "cocacola.jpg",
  "quantity" : 30,
  "status": true
}
###
@prodAdded = {{newProduct.response.body._id}}

###
PUT {{url}}/api/products/{{prodAdded}}
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
  "title" : "Coca cola",
  "description" : "Bebida cola",
  "price" : 101.10,
  "thumbnail" : "cocacola.jpg",
  "code" : "cocacola",
  "quantity" : 55,
  "status": true
}
###

DELETE {{url}}/api/products/{{prodAdded}}
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
###

GET  {{url}}/api/carts
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
###

###
# @name productForCard
GET {{url}}/api/products?limit=1&page=1&sort=asc
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###
@productCart = {{productForCard.response.body.payload.0._id}}

# @name newCart

POST  {{url}}/api/carts
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
    "product" : "{{productCart}}",
    "quantity" : 1
}

###
@newCartId = {{newCart.response.body.cart._id}}

###

GET  {{url}}/api/carts/{{newCartId}}
Authorization: Bearer {{access_token}}
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###
