@url = http://localhost:3000

###
POST {{url}}/api/products/
Content-Type: application/json

{
  "name" : "Coca cola",
  "description" : "Bebida cola",
  "price" : 101.10,
  "thumbnail" : "cocacola.jpg",
  "quantity" : 30,
  "status": true
}
###


# @name product
GET {{url}}/api/products

@pId = {{product.response.body.products.data.0._id}}

###
GET {{url}}/api/products/{{pId}}

###
POST {{url}}/api/products/
Content-Type: application/json

{
  "name" : "Coca cola 2",
  "description" : "Bebida cola",
  "price" : 101.10,
  "thumbnail" : "cocacola.jpg",
  "quantity" : 30,
  "status": true
}
###

# @name products
GET {{url}}/api/products

###
@pIdLast = {{product.response.body.products.data.0._id}}

DELETE {{url}}/api/products/{{pIdLast}}
###

POST {{url}}/api/users/
Content-Type: application/json

{
  "first_name": "Marcelo",
  "last_name": "Oliveto",
  "email": "marcelo.oliveto@gmail.com",
  "age": 53,
  "password" : "12345",
  "role": "admin"
}
